#!/bin/bash

# Workflow Admin Implementation - Quick Start Script
# This script sets up the file structure for the workflow admin feature

echo "🚀 Starting Workflow Admin Implementation Setup..."
echo ""

# Create directories
echo "📁 Creating directories..."
mkdir -p app/admin/workflows
mkdir -p components/admin
mkdir -p types
mkdir -p docs

# Create type definition file
echo "📝 Creating types/workflow-admin.ts..."
cat > types/workflow-admin.ts << 'EOF'
// Workflow Admin Type Definitions
// Generated by START_IMPLEMENTATION.sh

export interface WorkflowConfig {
  id: string;
  code: string;
  name: string;
  form_template_id: string | null;
  active: boolean;
  created_at: string;
  step_count?: number;
  instance_count?: number;
}

export interface WorkflowStepConfig {
  id: string;
  workflow_id: string;
  step_order: number;
  role_required: string;
  position_required: string | null;
  action_label: string;
  is_final: boolean;
  created_at: string;
}

export interface WorkflowStepFormData {
  step_order: number;
  role_required: string;
  position_required: string;
  action_label: string;
  is_final: boolean;
}

export interface WorkflowValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export interface WorkflowDetail extends WorkflowConfig {
  steps: WorkflowStepConfig[];
}

export interface Result<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}
EOF

# Create library file stub
echo "📝 Creating lib/workflow-admin.ts stub..."
cat > lib/workflow-admin.ts << 'EOF'
// Workflow Admin Data Access Layer
// Generated by START_IMPLEMENTATION.sh

import { supabase } from './supabase';
import type {
  WorkflowConfig,
  WorkflowStepConfig,
  WorkflowStepFormData,
  WorkflowValidationResult,
  WorkflowDetail,
  Result,
} from '@/types/workflow-admin';

const db = supabase as any;

// ─── Read Operations ──────────────────────────────────────────────────────────

export async function listWorkflows(): Promise<WorkflowConfig[]> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function getWorkflowWithSteps(workflowId: string): Promise<WorkflowDetail | null> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function listRolesForDropdown(): Promise<Array<{ id: string; name: string }>> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function listPositionsForDropdown(): Promise<Array<{ id: string; title: string; role: string }>> {
  // TODO: Implement
  throw new Error('Not implemented');
}

// ─── Validation ───────────────────────────────────────────────────────────────

export function validateWorkflowSteps(steps: WorkflowStepConfig[]): WorkflowValidationResult {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function checkStepDependencies(stepId: string): Promise<{ canDelete: boolean; reason?: string }> {
  // TODO: Implement
  throw new Error('Not implemented');
}

// ─── Write Operations ─────────────────────────────────────────────────────────

export async function createWorkflowStep(
  workflowId: string,
  stepData: WorkflowStepFormData
): Promise<Result<WorkflowStepConfig>> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function updateWorkflowStep(
  stepId: string,
  updates: Partial<WorkflowStepFormData>
): Promise<Result<WorkflowStepConfig>> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function deleteWorkflowStep(stepId: string): Promise<Result> {
  // TODO: Implement
  throw new Error('Not implemented');
}

export async function reorderWorkflowSteps(
  workflowId: string,
  newOrder: Array<{ id: string; step_order: number }>
): Promise<Result> {
  // TODO: Implement
  throw new Error('Not implemented');
}

// ─── Audit ────────────────────────────────────────────────────────────────────

export async function logWorkflowAudit(
  action: 'WORKFLOW_STEP_CREATED' | 'WORKFLOW_STEP_UPDATED' | 'WORKFLOW_STEP_DELETED' | 'WORKFLOW_STEPS_REORDERED',
  workflowId: string,
  actorId: string,
  payload: any
): Promise<void> {
  // TODO: Implement
  throw new Error('Not implemented');
}
EOF

# Create component stubs
echo "📝 Creating component stubs..."

cat > components/admin/WorkflowTable.tsx << 'EOF'
// Workflow Table Component
// Generated by START_IMPLEMENTATION.sh

'use client';

import type { WorkflowConfig } from '@/types/workflow-admin';

interface WorkflowTableProps {
  workflows: WorkflowConfig[];
  isLoading: boolean;
  onSelectWorkflow: (workflow: WorkflowConfig) => void;
}

export default function WorkflowTable({ workflows, isLoading, onSelectWorkflow }: WorkflowTableProps) {
  // TODO: Implement
  return (
    <div className="bg-white rounded-lg border border-pq-neutral-200 p-6">
      <p className="text-sm text-pq-neutral-500">WorkflowTable - TODO: Implement</p>
    </div>
  );
}
EOF

cat > components/admin/WorkflowStepEditor.tsx << 'EOF'
// Workflow Step Editor Component
// Generated by START_IMPLEMENTATION.sh

'use client';

import type { WorkflowStepConfig } from '@/types/workflow-admin';

interface WorkflowStepEditorProps {
  workflowId: string;
  steps: WorkflowStepConfig[];
  roles: Array<{ id: string; name: string }>;
  positions: Array<{ id: string; title: string; role: string }>;
  onStepsChange: () => void;
}

export default function WorkflowStepEditor({
  workflowId,
  steps,
  roles,
  positions,
  onStepsChange,
}: WorkflowStepEditorProps) {
  // TODO: Implement
  return (
    <div className="bg-white rounded-lg border border-pq-neutral-200 p-6">
      <p className="text-sm text-pq-neutral-500">WorkflowStepEditor - TODO: Implement</p>
    </div>
  );
}
EOF

cat > components/admin/WorkflowStepForm.tsx << 'EOF'
// Workflow Step Form Component
// Generated by START_IMPLEMENTATION.sh

'use client';

import type { WorkflowStepConfig, WorkflowStepFormData } from '@/types/workflow-admin';

interface WorkflowStepFormProps {
  mode: 'create' | 'edit';
  initialData?: WorkflowStepConfig;
  roles: Array<{ id: string; name: string }>;
  positions: Array<{ id: string; title: string; role: string }>;
  existingStepOrders: number[];
  onSubmit: (data: WorkflowStepFormData) => Promise<void>;
  onCancel: () => void;
}

export default function WorkflowStepForm({
  mode,
  initialData,
  roles,
  positions,
  existingStepOrders,
  onSubmit,
  onCancel,
}: WorkflowStepFormProps) {
  // TODO: Implement
  return (
    <div className="p-6">
      <p className="text-sm text-pq-neutral-500">WorkflowStepForm - TODO: Implement</p>
    </div>
  );
}
EOF

cat > components/admin/WorkflowStepDeleteDialog.tsx << 'EOF'
// Workflow Step Delete Dialog Component
// Generated by START_IMPLEMENTATION.sh

'use client';

import type { WorkflowStepConfig } from '@/types/workflow-admin';

interface WorkflowStepDeleteDialogProps {
  step: WorkflowStepConfig | null;
  isOpen: boolean;
  isLoading: boolean;
  onConfirm: (step: WorkflowStepConfig) => Promise<void>;
  onCancel: () => void;
}

export default function WorkflowStepDeleteDialog({
  step,
  isOpen,
  isLoading,
  onConfirm,
  onCancel,
}: WorkflowStepDeleteDialogProps) {
  // TODO: Implement
  return null;
}
EOF

# Create main page stub
echo "📝 Creating app/admin/workflows/page.tsx stub..."
cat > app/admin/workflows/page.tsx << 'EOF'
// Workflow Admin Page
// Generated by START_IMPLEMENTATION.sh

'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import AppShell from '@/components/layout/AppShell';
import LoadingState from '@/components/shared/LoadingState';
import PageHeader from '@/components/shared/PageHeader';
import WorkflowTable from '@/components/admin/WorkflowTable';
import WorkflowStepEditor from '@/components/admin/WorkflowStepEditor';
import type { WorkflowConfig, WorkflowStepConfig } from '@/types/workflow-admin';

export default function WorkflowsPage() {
  const { profile, loading: authLoading } = useAuth();
  const [workflows, setWorkflows] = useState<WorkflowConfig[]>([]);
  const [selectedWorkflow, setSelectedWorkflow] = useState<WorkflowConfig | null>(null);
  const [steps, setSteps] = useState<WorkflowStepConfig[]>([]);
  const [roles, setRoles] = useState<Array<{ id: string; name: string }>>([]);
  const [positions, setPositions] = useState<Array<{ id: string; title: string; role: string }>>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (authLoading) return;

    if (!profile) {
      setError('Not authenticated');
      setIsLoading(false);
      return;
    }

    if (profile.role !== 'admin') {
      setError('Access denied. Admin role required.');
      setIsLoading(false);
      return;
    }

    // TODO: Load data
    setIsLoading(false);
  }, [authLoading, profile]);

  if (authLoading) {
    return (
      <AppShell title="Workflow Configuration">
        <LoadingState message="Loading..." />
      </AppShell>
    );
  }

  if (error === 'Access denied. Admin role required.') {
    return (
      <AppShell title="Workflow Configuration">
        <div className="space-y-6">
          <PageHeader title="Approval Workflows" description="Configure approval pipeline steps and authorities" />
          <div className="bg-pq-danger-100 border border-pq-danger-100 rounded-lg p-6">
            <h3 className="font-semibold text-red-900 mb-2">Access Denied</h3>
            <p className="text-sm text-pq-danger-600">
              You do not have permission to configure workflows. Only administrators can access this feature.
            </p>
          </div>
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell title="Workflow Configuration">
      <div className="space-y-6">
        <PageHeader title="Approval Workflows" description="Configure approval pipeline steps and authorities" />

        {error && (
          <div className="bg-pq-danger-100 border border-pq-danger-100 rounded-lg p-4">
            <p className="text-xs text-pq-danger-600">{error}</p>
          </div>
        )}

        <WorkflowTable workflows={workflows} isLoading={isLoading} onSelectWorkflow={setSelectedWorkflow} />

        {selectedWorkflow && (
          <WorkflowStepEditor
            workflowId={selectedWorkflow.id}
            steps={steps}
            roles={roles}
            positions={positions}
            onStepsChange={() => {
              // TODO: Reload steps
            }}
          />
        )}
      </div>
    </AppShell>
  );
}
EOF

echo ""
echo "✅ File structure created successfully!"
echo ""
echo "📋 Next Steps:"
echo "1. Review WORKFLOW_ADMIN_IMPLEMENTATION_PLAN.md for detailed implementation guide"
echo "2. Review SURGICAL_MODE_GUIDE.md for safety guidelines"
echo "3. Review SYSTEM_DESIGN_DIAGRAM.md for architecture overview"
echo "4. Start implementing Phase 1: Foundation & Data Layer"
echo "   - Implement functions in lib/workflow-admin.ts"
echo "   - Add validation logic"
echo "   - Add audit logging"
echo "5. Move to Phase 2: UI Components"
echo "6. Continue through remaining phases"
echo ""
echo "🎯 Files created:"
echo "   - types/workflow-admin.ts"
echo "   - lib/workflow-admin.ts"
echo "   - app/admin/workflows/page.tsx"
echo "   - components/admin/WorkflowTable.tsx"
echo "   - components/admin/WorkflowStepEditor.tsx"
echo "   - components/admin/WorkflowStepForm.tsx"
echo "   - components/admin/WorkflowStepDeleteDialog.tsx"
echo ""
echo "🚀 Ready to start implementation!"
