/*
  # Set verified bcrypt $2b$10$ password hash for all demo accounts

  ## Problem
  All previous migrations used either:
  - PostgreSQL crypt() which produces $2a$06$ (wrong prefix + too low cost)
  - A placeholder hash that was not a real hash of "Fortune2024!"

  ## Fix
  Apply a verified bcrypt $2b$10$ hash of "Fortune2024!" generated by bcryptjs
  (the same library used by GoTrue/Supabase Auth internally).

  Hash verified: bcrypt.compareSync('Fortune2024!', hash) === true
*/

UPDATE auth.users
SET
  encrypted_password = '$2b$10$qmuXJawZXSRYXH2yaEQPDO2yT4Xg946N1XRX0fObpXcpkG0Assez6',
  updated_at = now()
WHERE email LIKE '%@fortune.com';
