/*
  # GRN (Goods Receipt Note) Schema

  ## Overview
  MVP GRN module for warehouse staff to record and close incoming deliveries.
  One GRN per delivery (which is one-per-PO). Warehouse staff fills in header
  fields (invoice, DR, dates) and per-item quantities received, then saves to
  close the transaction.

  ## New Tables

  ### grn_receipts
  GRN header. One per delivery. Auto-created when a delivery is marked delivered
  or when warehouse opens a GRN. Status: open → closed.
  - grn_number: auto-generated sequential number (GRN-YYYYMM-XXXX)
  - Links back to delivery_id → po_id → pr2 → pr1 via snapshots
  - Stores invoice_no, dr_no, dr_date, transaction_date from physical docs
  - received_by_id / received_by_name_snapshot: warehouse staff who closes it

  ### grn_items
  Per-line quantities received. One row per PO item.
  - quantity_ordered: from po_items (snapshot)
  - quantity_received: entered by warehouse staff
  - quantity_rejected: damaged/short (optional)
  - remarks: per-item notes

  ## GRN Number Generation
  Format: GRN-YYYYMM-XXXX (e.g., GRN-202604-0001)
  Generated by a DB function to avoid race conditions.

  ## Status
  - open: GRN created, not yet saved/closed
  - closed: GRN saved — transaction complete

  ## Security
  - RLS enabled
  - Warehouse: full CRUD (create, edit, close)
  - Procurement: read-only
  - Approver: read-only
  - Employee: read-only for own requisition GRNs (via delivery → requisitioner_id)
  - Supplier: no access (GRN is internal)
*/

-- ─── GRN number sequence ──────────────────────────────────────────────────────

CREATE SEQUENCE IF NOT EXISTS grn_number_seq START 1;

CREATE OR REPLACE FUNCTION generate_grn_number()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_seq int;
  v_prefix text;
BEGIN
  v_seq    := nextval('grn_number_seq');
  v_prefix := 'GRN-' || to_char(now(), 'YYYYMM');
  RETURN v_prefix || '-' || lpad(v_seq::text, 4, '0');
END;
$$;

-- ─── grn_receipts ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS grn_receipts (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- GRN identity
  grn_number                text UNIQUE NOT NULL DEFAULT generate_grn_number(),

  -- Linked delivery (one-per-delivery)
  delivery_id               uuid NOT NULL REFERENCES deliveries(id),

  -- Snapshots for immutable record
  po_number_snapshot        text NOT NULL DEFAULT '',
  pr2_number_snapshot       text NOT NULL DEFAULT '',
  pr1_number_snapshot       text NOT NULL DEFAULT '',
  supplier_name_snapshot    text NOT NULL DEFAULT '',
  department_name_snapshot  text NOT NULL DEFAULT '',
  purpose                   text NOT NULL DEFAULT '',
  warehouse                 text NOT NULL DEFAULT '',
  delivery_address          text NOT NULL DEFAULT '',

  -- Physical document fields entered by warehouse
  invoice_no                text NOT NULL DEFAULT '',
  dr_no                     text NOT NULL DEFAULT '',
  dr_date                   date,
  transaction_date          date NOT NULL DEFAULT CURRENT_DATE,

  -- Warehouse staff
  received_by_id            uuid REFERENCES auth.users(id),
  received_by_name_snapshot text NOT NULL DEFAULT '',
  received_by_position_snapshot text NOT NULL DEFAULT '',

  -- Status
  status                    text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'closed')),

  -- Optional notes
  remarks                   text NOT NULL DEFAULT '',

  -- Timestamps
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  closed_at                 timestamptz,

  UNIQUE(delivery_id)
);

ALTER TABLE grn_receipts ENABLE ROW LEVEL SECURITY;

-- Warehouse: full access
CREATE POLICY "Warehouse can read all GRNs"
  ON grn_receipts FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

CREATE POLICY "Warehouse can insert GRNs"
  ON grn_receipts FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

CREATE POLICY "Warehouse can update open GRNs"
  ON grn_receipts FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

-- Procurement: read-only
CREATE POLICY "Procurement can read all GRNs"
  ON grn_receipts FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'procurement'
    )
  );

-- Approver: read-only
CREATE POLICY "Approvers can read all GRNs"
  ON grn_receipts FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'approver'
    )
  );

-- Employee: read GRNs for their own requisition's delivery
CREATE POLICY "Employee can read own requisition GRNs"
  ON grn_receipts FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM deliveries d
      WHERE d.id = grn_receipts.delivery_id
        AND d.requisitioner_id = auth.uid()
    )
  );

-- ─── grn_items ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS grn_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  grn_id              uuid NOT NULL REFERENCES grn_receipts(id) ON DELETE CASCADE,

  -- Link back to po_item
  po_item_id          uuid REFERENCES po_items(id),

  -- Snapshots
  item_order          int NOT NULL DEFAULT 0,
  item_code           text NOT NULL DEFAULT '',
  description         text NOT NULL DEFAULT '',
  unit_of_measure     text NOT NULL DEFAULT '',

  -- Quantities
  quantity_ordered    numeric(14,4) NOT NULL DEFAULT 0,
  quantity_received   numeric(14,4) NOT NULL DEFAULT 0,
  quantity_rejected   numeric(14,4) NOT NULL DEFAULT 0,

  -- Unit price snapshot for value calculation
  unit_price          numeric(14,4) NOT NULL DEFAULT 0,

  -- Per-item remarks
  remarks             text NOT NULL DEFAULT '',

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE grn_items ENABLE ROW LEVEL SECURITY;

-- Warehouse: full access
CREATE POLICY "Warehouse can read GRN items"
  ON grn_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

CREATE POLICY "Warehouse can insert GRN items"
  ON grn_items FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

CREATE POLICY "Warehouse can update GRN items"
  ON grn_items FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'warehouse'
    )
  );

-- Procurement: read-only
CREATE POLICY "Procurement can read GRN items"
  ON grn_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'procurement'
    )
  );

-- Approver: read-only
CREATE POLICY "Approvers can read GRN items"
  ON grn_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p JOIN roles r ON r.id = p.role_id
      WHERE p.id = auth.uid() AND r.name = 'approver'
    )
  );

-- Employee: read GRN items for own requisition
CREATE POLICY "Employee can read own requisition GRN items"
  ON grn_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM grn_receipts g
      JOIN deliveries d ON d.id = g.delivery_id
      WHERE g.id = grn_items.grn_id
        AND d.requisitioner_id = auth.uid()
    )
  );

-- ─── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_grn_receipts_delivery_id ON grn_receipts(delivery_id);
CREATE INDEX IF NOT EXISTS idx_grn_receipts_status      ON grn_receipts(status);
CREATE INDEX IF NOT EXISTS idx_grn_items_grn_id         ON grn_items(grn_id);
CREATE INDEX IF NOT EXISTS idx_grn_items_po_item_id     ON grn_items(po_item_id);
